# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                      <server>
                          <id>thirard-logger-repo</id>
                          <username>${{ secrets.USER }}</username>
                          <password>${{ secrets.TOKEN }}</password>
                      </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml
                
      - name: Afficher le répertoire ~/.m2
        run: |
          ls -la ~/.m2  # Liste les fichiers dans le répertoire ~/.m2
          cat ~/.m2/settings.xml  # Affiche le contenu du fichier settings.xml
      
      - name: Have GitHub Actions Build Maven Project
        run: |
          mvn -B package --file pom.xml
          mkdir staging && cp target/*.jar staging

      - name: Set up a cache for Maven
        uses: actions/cache@v4.2.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: $ {{ runner.os }}-m2

      - name: Persist workflow data as artifact
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: github-actions-artifact
          path: staging
