# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created, edited]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                      <server>
                          <id>thirard-logger-repo</id>
                          <username>${{ secrets.USER }}</username>
                          <password>${{ secrets.TOKEN }}</password>
                      </server>
                      <server>
                          <id>thirard-akeneo-upload-jpg</id>
                          <username>${{ secrets.USER }}</username>
                          <password>${{ secrets.TOKEN }}</password>
                      </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml
                
      - name: Afficher le répertoire ~/.m2
        run: |
          ls -la ~/.m2  # Liste les fichiers dans le répertoire ~/.m2
          cat ~/.m2/settings.xml  # Affiche le contenu du fichier settings.xml
      
      - name: Build with Maven
        run: mvn clean compile assembly:single
  
      - name: Deploy to GitHub Packages
        run: mvn deploy -Dmaven.resolver.transport=wagon --settings ~/.m2/settings.xml
